### ISSUE TITLE
Fix client/nginx/default.conf file

### ISSUE THREAD

**Issue by CodyJReed** [BZAghalarov/multi-docker#1]
I believe this might be contributing to a failure when trying to build and push a docker image to the owner's repo. The file appears misspelled as defualt.conf

**Comment by BZAghalarov** [comment]
Hi,
@CodyJReed thanks for your support.
But I can't understand where was mispelled. I have mispelled "defualt" as "defaul" in client/Dockerfile
and correted it.But client folder is not uploaded after this change.

**Comment by CodyJReed** [comment]
You named the file defualt.conf in the nginx directory of the client folder

**Comment by BZAghalarov** [comment]
I have renamed it and code passed test in Travis and uploaded to docker hub.
If possible give me hint how you find this typo

**Comment by CodyJReed** [comment]
I knew that the cause was some where between the shared relationship of the Dockerfile and the default.conf file; considering all your other files uploaded successfully.
